### PR TITLE
тестовая страница + nodemon для разработки

### PR DESCRIPTION
**Pull request by Damir-k**
Первый пулл :)

### CODE REVIEW

**Comment by Damir-k** [comment]
Подтверждаю

**Comment by stennie** [comment]
Hi @Damir-k,

It looks like you accidentally submitted a PR to merge to the base template repo of `fl0zone/template-nodejs` instead of the main branch for your own repo: https://github.com/Damir-k/vtb-hackaton-5/tree/main

Regards,
Stennie

**Comment by Damir-k** [comment]
Yep! An accident, sorry

**Comment by stennie** [comment]
No worries @Damir-k. Hope your hackathon project went well 👍 

Regards,
Stennie

**Pull request closed without merging**
